export { default } from "./src/wallet-manager-btc.js";
export { default as WalletAccountBtc } from "./src/wallet-account-btc.js";
export type FeeRates = any;
export type KeyPair = any;
export type TransactionResult = any;
export type TransferOptions = any;
export type TransferResult = any;
export type BtcWalletConfig = import("./src/wallet-manager-btc.js").BtcWalletConfig;
export type BtcTransaction = import("./src/wallet-account-btc.js").BtcTransaction;
export type BtcTransfer = import("./src/wallet-account-btc.js").BtcTransfer;
