export { default } from "./src/wallet-manager-btc.js";
export { default as WalletAccountReadOnlyBtc } from "./src/wallet-account-read-only-btc.js";
export { default as WalletAccountBtc } from "./src/wallet-account-btc.js";
export type BtcTransactionReceipt = import("bitcoinjs-lib").Transaction;
export type FeeRates = import("@wdk/wallet").FeeRates;
export type KeyPair = import("@wdk/wallet").KeyPair;
export type TransactionResult = import("@wdk/wallet").TransactionResult;
export type TransferOptions = import("@wdk/wallet").TransferOptions;
export type TransferResult = import("@wdk/wallet").TransferResult;
export type BtcTransaction = import("./src/wallet-account-read-only-btc.js").BtcTransaction;
export type BtcWalletConfig = import("./src/wallet-account-read-only-btc.js").BtcWalletConfig;
